<?php

$PREGUNTAS_A = [
'Asiste puntualmente a su clase',
'Da a conocer los objetivos, contenidos y criterios de evaluación del curso al iniciar el cuatrimestre.',
'Demuestra dominio de los contenidos que imparte',
'Prepara sus clases',
'Explica claramente la clase',
'Muestra interés por el curso',
'Implementa diferentes estrategias didácticas para el aprendizaje',
'Promueve situaciones que favorecen que el estudiante aprenda por sí mismo',
'Adapta las actividades de enseñanza a las necesidades de los estudiantes',
'Impulsa un ambiente de confianza que favorece la interacción y el aprendizaje',
'Promueve el uso de las TICs (correo, plataformas, blog, redes sociales)',
'Emplea diversas actividades e instrumentos de evaluación acordes a los propósitos del curso',
'Respeta los criterios acordados para la evaluación del aprendizaje',
'Retroalimenta a los estudiantes respecto a sus fortalezas y áreas de mejora',
'Estimula actitudes de tolerancia y respeto a la diversidad y opiniones que facilitan la convivencia',
'Recomendaría a este profesor para que continúe impartiendo esta materia',
'Me gustaría llevar otro curso con este profesor',
'Asesora de manera individual o grupal, de acuerdo con las necesidades que presentan los estudiantes'
];

$AUTOEVALUACION = [
'01.  Asisto y soy puntual a clase',
'02.  Doy a conocer los objetivos, contenidos y criterios de evaluación del curso al iniciar el cuatrimestre',
'03.  Domino los contenidos que imparto',
'04.  Preparo las clases',
'05.  Explico claramente la clase',
'06.  Muestro y transmito interés por el curso',
'07.  Implemento diferentes estrategias didácticas para el aprendizaje',
'08.  Promuevo situaciones e implemento estrategias que favorecen que el estudiante aprenda por sí mismo',
'09.  Adecúo las actividades de enseñanza a las necesidades de los estudiantes',
'10. Impulso un ambiente de confianza que favorece la interacción y el aprendizaje',
'11. Promuevo el uso de las TIC´s para el desarrollo de actividades en el proceso de enseñanza-aprendizaje (correo, plataformas, blog, redes sociales)',
'12. Empleo diversas actividades e instrumentos de evaluación acordes a los propósitos del curso',
'13. Respeto los criterios de evaluación acordados',
'14. Retroalimento a los estudiantes con los temas o áreas de oportunidad',
'15. Genero actitudes de tolerancia y respeto a la diversidad y opiniones que facilitan la convivencia',
'16. Participo en reuniones de profesores convocadas por el Director de Carrera, Secretaría Académica o Rectoría',
'17. Cumplo con actividades académicas-administrativas (planeación de la asignatura captura y entrega de calificaciones, exámenes y reportes)',
'18. Participo en la organización de eventos académicos de la UTeM',
'19. Participo en las actividades a las que me convoca la dirección de carrera (promoción de los PE, aplicación de CENEVAL, etc)',
'20. Participo en actividades de actualización y capacitación para mejorar la práctica docente',
'21. Recibo en tiempo y forma el material didáctico y la planeación académica',
'22. Participo en reuniones de academia para el desarrollo de actividades de la enseñanza-aprendizaje',
'23. Cumplo con el 100% de los contenidos temáticos programados en el cuatrimestre',
'24. Asesora de manera individual o grupal, de acuerdo con las necesidades que presentan los estudiantes',
'25. Colaboro en los procesos de planeación y evaluación de la UTeM (proyectos, CA, PROMEP, PIFI, POA, etc)',
'26. Participo en las actualizaciones y reestructuraciones curriculares',
];

$PREGUNTAS_D = [
'01.  Asistió y fue puntual a clase',
'02.  Demuestra dominio de los contenidos que imparte',
'03.  Prepara sus clases',
'04.  Explica claramente la clase',
'05.  Muestra interés por el curso',
'06.  Implementa diferentes estrategias didácticas para el aprendizaje',
'07.  Promueve situaciones que favorecen que el estudiante aprenda por sí mismo',
'08.  Adapta las actividades de enseñanza a las necesidades de los estudiantes',
'09.  Impulsa un ambiente de confianza que favorece la interacción y el aprendizaje',
'10. Promueve el uso de las TIC´s (correo, plataformas, blog, redes sociales)',
'11. Emplea diversas actividades e instrumentos de evaluación acordes a los propósitos del curso',
'12. Respeta los criterios acordados para la evaluación del aprendizaje',
'13. Retroalimenta a los estudiantes respecto a sus fortalezas y áreas de mejora',
'14. Estimula actitudes de tolerancia y respeto a la diversidad y opiniones que facilitan la convivencia',
'15. Cumplió con actividades académicas-administrativas en tiempo y forma (planeación de la asignatura, captura y entrega de calificaciones, exámenes y reportes)',
'16. Participó en la organización de eventos académicos de la UTeM',
'17. Participó en las actividades a las que convoca la dirección de carrera (promoción de los PE, aplicación de CENEVAL, etc)',
'18. Participó en actividades de actualización y capacitación para mejorar la práctica docente',
'19. Participó en reuniones de profesores convocadas por el Director de Carrera, Secretaría Académica o Rectoría',
'20. Colaboró en los procesos de planeación y evaluación de la UTeM (proyectos, CA, PROMEP, PIFI, POA, etc)',
'21. Participó en las actualizaciones y reestructuraciones curriculares',
'22. Participó en las reuniones de academia los avances o productos del curso',
'23. Asesora de manera individual o grupal, de acuerdo con las necesidades que presentan los estudiantes',
'24. Las actividades planificadas por el docente, se cumplieron de acuerdo al FOR-GEC-01-A Planeación de la Asignatura',
'25. Cumplió los horarios establecidos según la planeación',
'26. Cumplió con el 100% de los contenidos temáticos programados en el cuatrimestre',
];

?>